  !-----------------------------------------------------------------
  !    This module was auto-generated by process_model,
  !    and then edited to match the signatures required.
  !
  !-----------------------------------------------------------------
  
module cg_drag_ML_mod


    implicit none

    public cg_drag_ML_init, &
        cg_drag_ML, &
        cg_drag_ML_end

    contains

    subroutine cg_drag_ML_init(model_dir, model_name)
        ! Parameters
        character(*) :: model_dir, model_name
    end subroutine cg_drag_ML_init

    subroutine cg_drag_ML(uuu, vvv, psfc, lat, gwfcng_x, gwfcng_y)
        real, dimension(:,:,:), intent(in)    :: uuu, vvv
        real, dimension(:,:),   intent(in)    :: lat, psfc

        real, dimension(:,:,:), intent(out), target   :: gwfcng_x, gwfcng_y
    end subroutine cg_drag_ML

    subroutine cg_drag_ML_end()
    end subroutine cg_drag_ML_end

end module cg_drag_ML_mod
